"""Turn the AI-written Markdown review brief into a downloadable Word document."""
from __future__ import annotations

import io
import re
from datetime import datetime

import pandas as pd
from docx import Document
from docx.shared import Pt, RGBColor

BRAND = RGBColor(0x1F, 0x4E, 0x79)


def _add_inline(paragraph, text: str) -> None:
    """Render **bold** and *italic* spans inside a paragraph."""
    for part in re.split(r"(\*\*[^*]+\*\*|\*[^*]+\*)", text):
        if not part:
            continue
        if part.startswith("**") and part.endswith("**"):
            paragraph.add_run(part[2:-2]).bold = True
        elif part.startswith("*") and part.endswith("*") and len(part) > 2:
            paragraph.add_run(part[1:-1]).italic = True
        else:
            paragraph.add_run(part)


def _add_md_table(doc: Document, lines: list[str]) -> None:
    rows = [[c.strip() for c in ln.strip().strip("|").split("|")] for ln in lines
            if not re.fullmatch(r"\s*\|?[\s:\-|]+\|?\s*", ln)]
    if not rows:
        return
    width = max(len(r) for r in rows)
    table = doc.add_table(rows=len(rows), cols=width)
    table.style = "Light Grid Accent 1"
    for i, row in enumerate(rows):
        for j in range(width):
            cell = table.cell(i, j)
            cell.text = ""
            _add_inline(cell.paragraphs[0], row[j] if j < len(row) else "")
            if i == 0:
                for run in cell.paragraphs[0].runs:
                    run.bold = True


def _add_df_table(doc: Document, df: pd.DataFrame) -> None:
    df = df.round(1).reset_index().rename(columns={"index": "District"})
    table = doc.add_table(rows=1, cols=len(df.columns))
    table.style = "Light Grid Accent 1"
    for j, col in enumerate(df.columns):
        table.cell(0, j).text = str(col)
    for _, r in df.iterrows():
        cells = table.add_row().cells
        for j, v in enumerate(r):
            cells[j].text = f"{v:.1f}" if isinstance(v, float) else str(v)


def markdown_to_docx(markdown: str, appendix: pd.DataFrame | None = None, source: str = "") -> bytes:
    doc = Document()
    doc.styles["Normal"].font.name = "Calibri"
    doc.styles["Normal"].font.size = Pt(10.5)

    lines = markdown.splitlines()
    i = 0
    while i < len(lines):
        line = lines[i].rstrip()
        stripped = line.strip()
        if stripped.startswith("|"):
            block = []
            while i < len(lines) and lines[i].strip().startswith("|"):
                block.append(lines[i])
                i += 1
            _add_md_table(doc, block)
            continue
        m = re.match(r"^(#{1,4})\s+(.*)", stripped)
        if m:
            h = doc.add_heading(m.group(2).replace("**", ""), level=min(len(m.group(1)), 3))
            for run in h.runs:
                run.font.color.rgb = BRAND
        elif re.match(r"^[-*•]\s+", stripped):
            style = "List Bullet 2" if line.startswith(("  ", "\t")) else "List Bullet"
            _add_inline(doc.add_paragraph(style=style), re.sub(r"^[-*•]\s+", "", stripped))
        elif re.match(r"^\d+[.)]\s+", stripped):
            _add_inline(doc.add_paragraph(style="List Number"), re.sub(r"^\d+[.)]\s+", "", stripped))
        elif stripped in ("---", "***"):
            pass
        elif stripped:
            _add_inline(doc.add_paragraph(), stripped)
        i += 1

    if appendix is not None and not appendix.empty:
        doc.add_page_break()
        h = doc.add_heading("Annex: District Indicator Table (computed from source data)", level=2)
        for run in h.runs:
            run.font.color.rgb = BRAND
        _add_df_table(doc, appendix)

    foot = doc.add_paragraph()
    foot.add_run(
        f"\nGenerated by InsightAI on {datetime.now():%d %b %Y, %H:%M}. Source dataset: {source or 'uploaded file'}. "
        "Figures are computed from the source data; interpretations are AI-generated and should be verified."
    ).italic = True

    buf = io.BytesIO()
    doc.save(buf)
    return buf.getvalue()
